/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai-matcher` | `/ai-matcher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/faves` | `/faves`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movie-favorites` | `/movie-favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/restaurants` | `/restaurants`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ai-matcher` | `/ai-matcher`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/faves` | `/faves`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movie-favorites` | `/movie-favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/restaurants` | `/restaurants`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ai-matcher${`?${string}` | `#${string}` | ''}` | `/ai-matcher${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/faves${`?${string}` | `#${string}` | ''}` | `/faves${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movie-favorites${`?${string}` | `#${string}` | ''}` | `/movie-favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movies${`?${string}` | `#${string}` | ''}` | `/movies${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/restaurants${`?${string}` | `#${string}` | ''}` | `/restaurants${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/swipe${`?${string}` | `#${string}` | ''}` | `/swipe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai-matcher` | `/ai-matcher`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/faves` | `/faves`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movie-favorites` | `/movie-favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/restaurants` | `/restaurants`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownInputParams; };
    }
  }
}
